# Generated by Django 4.2.5 on 2023-10-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.BigIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_deletion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
